name: chall2026-pied-pipyer

services:
  pied-pipyer:
    image: athack-ctf/chall2026-pied-pipyer:latest
    container_name: chall2026-pied-pipyer
    build:
      context: .
      dockerfile: source/Dockerfile
    ports:
      - "53018:80"